image: node:18

stages:
  - install
  - build

variables:
  NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/.npm"
  NODE_MODULES: "$CI_PROJECT_DIR/node_modules"

cache:
  paths:
    - .npm/
    - node_modules/

# Install dependencies
install_dependencies:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

# Build application
build:
  stage: build
  script:
    - npm run build -- --configuration=production
  artifacts:
    paths:
      - dist/
  dependencies:
    - install_dependencies
